
# NumPy 基础与实践

本 Notebook 包含 NumPy 的核心知识点和示例代码，帮助学生掌握 NumPy 的基本操作和高级功能。

首先，确保你已经安装了 numpy 库。如果没有安装，可以使用以下命令进行安装：
NumPy 提供了丰富的矩阵操作功能，包括：
创建矩阵：从列表、全零、全 1、单位矩阵等。
矩阵运算：加法、减法、逐元素乘法、矩阵乘法等。
矩阵转置：行和列互换。
矩阵求逆：计算矩阵的逆。
矩阵行列式：计算矩阵的行列式。
矩阵的迹：计算主对角线元素的和。
特征值和特征向量：计算矩阵的特征值和特征向量。
矩阵的秩：计算矩阵的秩。
矩阵分解：LU 分解、QR 分解、SVD 等。
矩阵拼接：垂直和水平拼接。
矩阵切片和索引：提取子矩阵。
矩阵广播：支持不同形状数组的逐元素操作。
矩阵统计操作：求和、均值、方差等。

TODO：
1. 运行以下代码，观察运行结果


In [1]:
#pip install numpy

In [3]:

## 1. 基础操作

### 1.1 创建数组

import numpy as np

# 创建一个形状为 (3, 3) 的全零数组
zeros_array = np.zeros((3, 3))
print("全零数组:\n", zeros_array)

# 创建一个形状为 (2, 4) 的全 1 数组
ones_array = np.ones((2, 4))
print("全 1 数组:\n", ones_array)

# 创建一个从 0 到 9 的一维数组
range_array = np.arange(10)
print("0 到 9 的数组:", range_array)

全零数组:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
全 1 数组:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0 到 9 的数组: [0 1 2 3 4 5 6 7 8 9]


数组属性

In [16]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

# 数组的形状
print("数组形状:", arr.shape)

# 数组的维度
print("数组维度:", arr.ndim)

# 数组的数据类型
print("数据类型:", arr.dtype)

数组形状: (2, 3)
数组维度: 2
数据类型: int64


数组变形

In [10]:
# 将一维数组变形为 (2, 5) 的二维数组
arr = np.arange(10)
reshaped_arr = arr.reshape(2, 5)
print("变形后的数组:\n", reshaped_arr)

# 将二维数组展平为一维数组
arr = np.array([[1, 2], [3, 4]])
flattened_arr = arr.flatten()
print("展平后的数组:", flattened_arr)

变形后的数组:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
展平后的数组: [1 2 3 4]


数组拼接

In [11]:
# 按行拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("按行拼接后的数组:", concatenated_arr)

# 按列拼接
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_arr = np.concatenate((arr1, arr2), axis=1)
print("按列拼接后的数组:\n", concatenated_arr)

按行拼接后的数组: [1 2 3 4 5 6]
按列拼接后的数组:
 [[1 2 5 6]
 [3 4 7 8]]


23300680008郭行健

3. 数学运算

3.1 基本运算

In [12]:
arr = np.array([1, 2, 3, 4, 5])

# 数组元素的和
print("数组元素和:", np.sum(arr))

# 数组元素的平均值
print("数组平均值:", np.mean(arr))

# 数组元素的标准差
print("数组标准差:", np.std(arr))

数组元素和: 15
数组平均值: 3.0
数组标准差: 1.4142135623730951


In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 矩阵乘法
result = np.dot(A, B)
print("矩阵乘积:\n", result)

矩阵乘积:
 [[19 22]
 [43 50]]


In [14]:
# 标量与数组的广播
arr = np.array([[1, 2, 3], [4, 5, 6]])
s = 2
result = arr + s
print("广播加法结果:\n", result)

# 数组与数组的广播
A = np.array([[1, 2, 3]])
B = np.array([[1], [2], [3]])
result = A + B
print("广播加法结果:\n", result)

广播加法结果:
 [[3 4 5]
 [6 7 8]]
广播加法结果:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [15]:
切片

NameError: name '切片' is not defined

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 获取第二行的所有元素
print("第二行:", arr[1, :])

# 获取第三列的所有元素
print("第三列:", arr[:, 2])

# 获取子数组 [[2, 3], [5, 6]]
print("子数组:\n", arr[0:2, 1:3])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# 提取所有大于 3 的元素
result = arr[arr > 3]
print("大于 3 的元素:", result)