PyTorch 是一个基于 Torch 库的开源机器学习框架，由 Facebook 的 AI 研究团队开发并维护。它广泛应用于深度学习研究，因其灵活性和动态计算图而备受青睐。以下是PyTorch核心组件：\
torch.Tensor\
张量（Tensor）：类似于 NumPy 的 ndarray，并且支持自动求导和 GPU 加速。\
操作：提供各种数学运算、矩阵操作等功能。\
<br>
nn.Module
模块（Module）：用于定义神经网络层和整个模型。
继承：通过继承 nn.Module 类来创建自定义层和模型。\
<br>
autograd
自动求导：用于计算梯度，支持链式法则。\
<br>
optim
优化器（Optimizer）：提供多种优化算法，如 SGD、Adam、RMSprop 等。\
简单易用：通过定义优化器对象并调用 step() 方法来更新参数。\
<br>
DataLoader\
数据加载器：用于加载和预处理数据集，支持批量处理、打乱数据等。\
方便集成：与 torchvision 等库配合使用，简化数据准备过程。


先选择使用的设备

In [ ]:
import torch

# 检查是否有可用的 GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
# 检查Mac上是否有可用的 MPS
elif torch.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")


Using device: mps


张量（tensor）创建

In [59]:
import torch
x = torch.arange(4)
y = torch.arange(6, dtype=torch.float32).reshape(2,-1)
print(x)
print(y)

tensor([0, 1, 2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])


更多创建方法

In [52]:
import torch
import numpy as np
print(torch.empty(3,dtype=torch.int32))#int32
print(torch.zeros(2,3)) #float32
print(torch.rand(2,3))#float32
print(torch.randn(2,3))#float32
print(torch.tensor([1,2.0,3]))#float32
print(torch.tensor(np.array([3.,4.])))#float64



tensor([0, 0, 0], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5537, 0.3953, 0.8571],
        [0.6396, 0.7403, 0.6766]])
tensor([[1.5152, 0.3698, 0.2815],
        [0.5603, 0.6311, 1.3469]])
tensor([1., 2., 3.])
tensor([3., 4.], dtype=torch.float64)


张量属性

In [ ]:
import torch
import numpy as np

# 创建一个基于现有数据的张量
data = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.tensor(data)

# 获取张量的各种属性
shape = x.shape
dtype = x.dtype
device = x.device
dimensions = x.dim()
num_elements = x.numel()
is_cpu = x.is_cpu
is_cuda = x.is_cuda

# 打印属性
print("Tensor x:")
print(x)
print("\nShape of Tensor x:", shape)
print("Dtype of Tensor x:", dtype)
print("Device of Tensor x:", device)
print("Dimensions of Tensor x:", dimensions)
print("Number of Elements in Tensor x:", num_elements)
print("Is Tensor on CPU:", is_cpu)
print("Is Tensor on CUDA:", is_cuda)


运算符操作-按元素运算

In [1]:
import torch

x = torch.tensor([1.,2,3,4])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y


(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]))

运算符操作-更多按元素运算

In [2]:
import torch

x = torch.tensor([-2.,-1,0,1,2])
x.exp(),x.sigmoid(),x.relu(),x.tanh()

(tensor([0.1353, 0.3679, 1.0000, 2.7183, 7.3891]),
 tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808]),
 tensor([0., 0., 0., 1., 2.]),
 tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640]))

In [ ]:
# squeeze
x=torch.randn(1, 3, 4, 1)
x_squeeze = x.squeeze()
x.shape, x_squeeze.shape


In [ ]:
# unsqueeze
x=torch.randn(3, 4)
x_0 = x.unsqueeze(0)
x_1 = x.unsqueeze(1)
x.shape, x_0.shape, x_1.shape

In [ ]:
import torch

# 创建张量
x = torch.tensor([1, 2, 3])
y = torch.zeros(3, 4)
z = torch.rand(2, 2)
w = torch.tensor([[1.0, 2.0], [1.2, 1.6]])
#x,y,z,w

# 形状变换
x_view = x.view(1, 3)
x_reshape = x.reshape(-1, 1)
x_transpose = z.transpose(0, 1)
x.shape, x_view, x_reshape, x_transpose, w.T, w.flatten()


In [ ]:

# 切片
x_slice = w[:, :1]

# 掩码

# 使用 torch.where 保持形状
masked_w1 = w[w>1.6]
masked_w2 = torch.where(w > 1.6, w, torch.tensor(0.0)) 
x_slice,masked_w1,masked_w2

In [ ]:
# 连续存储
x_contiguous = torch.randn(3, 4).t().contiguous()
x_contiguous

In [ ]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
# 步长视图
x_as_strided = x.as_strided(size=(2, 2), stride=(2, 2))
# 切片
x_slice = x[:, :2]
x,x_as_strided,x_slice


In [ ]:
# 填充
x_pad = torch.tensor([[1, 2], [3, 4]])
x_padded = F.pad(x_pad, pad=(1, 1, 1, 1), mode='constant', value=0)
x_pad,x_padded

In [ ]:
# 堆叠
a_stack = torch.tensor([1, 2])
b_stack = torch.tensor([3, 4])
c_stack = torch.stack((a_stack, b_stack))
a_stack,b_stack,c_stack

运算符操作-张量连结（concatenate）

In [3]:
import torch

X = torch.tensor([1,2,3,4]).reshape(2,-1)
Y = torch.tensor([2,2,2,2]).reshape(-1,2)
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[1, 2],
         [3, 4],
         [2, 2],
         [2, 2]]),
 tensor([[1, 2, 2, 2],
         [3, 4, 2, 2]]))

向量矩阵运算

In [4]:
a = torch.tensor([4,4])
b = torch.tensor([1,1])
w = torch.tensor([[1,1],[2,2],[3,3]])
m = torch.tensor([[1,2],[3,4]])
x1=torch.matmul(a,b)#向量点积
x2=torch.matmul(w,b)#矩阵向量乘法
x3=torch.mm(w,m)#矩阵乘法
x4=torch.matmul(w,m)#高维张量乘法
x1,x2,x3,x4

(tensor(8),
 tensor([2, 4, 6]),
 tensor([[ 4,  6],
         [ 8, 12],
         [12, 18]]),
 tensor([[ 4,  6],
         [ 8, 12],
         [12, 18]]))

张量拼接操作

In [88]:
import torch
import numpy as np

# 创建一个形状为 (2, 2, 4) 的三维张量
tensor_3d_0 = torch.zeros(16).reshape(2, 2, 4)
tensor_3d_1 = torch.ones(16).reshape(2, 2, 4)
# 使用 torch.cat 将两个三维张量拼接成四维张量
tensor_4d_cat = torch.cat((tensor_3d_0.unsqueeze(0), tensor_3d_1.unsqueeze(0)), dim=0)
tensor_3d_0, tensor_3d_1,tensor_4d_cat

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.]],
 
          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]))

向量化

In [18]:
import torch # 导入PyTorch库
import time #导入时间库
# 检查是否有可用的GPU，并选择合适的设备
torch.manual_seed(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#device = torch.device("mps" if torch.mps.is_available() else "cpu")
print(f"Using device: {device}")
# 创建两个一百万维度的随机张量a和b
a = torch.rand(1000000, device=device,dtype=torch.float32)#device=device,
b = torch.rand(1000000,device=device,dtype=torch.float32)
#c = torch.zeros(1,device=device,dtype=torch.float64)

# 非向量化版本
c = 0
start_time = time.time()
an=a.numpy()
bn=b.numpy()
for i in range(len(a)):
    c += a[i] * b[i]
end_time = time.time()
print("%.9f"%c)
print("For循环方法运行时间: %.6f ms" % ((end_time - start_time) * 1000))

# 向量化版本
start_time = time.time() # 记录当前时间
c = torch.dot(a, b)
end_time = time.time()
print("%.9f"%c) # 使用item()方法将单元素张量转换为Python标量
print("向量化方法运行时间: %.6f ms" % ((end_time - start_time) * 1000))


Using device: cpu
249827.187500000
For循环方法运行时间: 2627.543926 ms
249860.937500000
向量化方法运行时间: 0.284910 ms
